language: node_js
node_js:
  - "8"
  - "7"
  - "6"
cache:
  yarn: true
before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - yarn install
  - greenkeeper-lockfile-update
script: npm run build
after_script: greenkeeper-lockfile-upload

# notifications:
#   email:
#     - john.doe@example.com
